### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by fitojb** [michaldaniel/Ebook-Viewer#8]
Currently, this application can’t be translated. Please consider using a framework like Gettext so that translators can provide localized UI files in the future :)

**Comment by michaldaniel** [comment]
Never done that before but it looks fairly straightforward, should be ready soon.

**Comment by michaldaniel** [comment]
Ready for translation (should be) and I also added Polish translation to start.

**Comment by fitojb** [comment]
Thanks, that was fast! I hereby attach an initial Spanish translation (.po and .mo), was going to attempt doing a pull request but figured out it’d be faster to just attach it here. :)

[es.po.zip](https://github.com/michaldaniel/Ebook-Viewer/files/523859/es.po.zip)

**Comment by michaldaniel** [comment]
@fitojb Do it for some git fame. You just have to add those files in `po/` directory and add a line to `Makefile`

Just like the last one here:
```
install-locale:
   install -d ${EBOOKVIEWER_DIR}/locale/pl
   install -d ${EBOOKVIEWER_DIR}/locale/pl/LC_MESSAGES
   install -m 644 po/pl.mo ${EBOOKVIEWER_DIR}/locale/pl/LC_MESSAGES/easy-ebook-viewer.mo
```
Just for es since it's first time this translation is introduced.

If you don't care just ignore me and I'll add them tomorrow evening. But in any case please mail me how to add you to about app dialog in translators credits.

**Comment by quatrecouleurs** [comment]
Nice. I've done is a French one as well :)

[fr.po.zip](https://github.com/michaldaniel/Ebook-Viewer/files/525737/fr.po.zip)

**Comment by michaldaniel** [comment]
I uploaded your translations @quatrecouleurs @fitojb but GtkAboutDialog translator credits allow me to only set one string for the "current translator" so now each translator can trasnlate "Michał Daniel (english translation)" to replace this with their own credit. I added instruction in non displayed translatable string since `pygettext` doesn't implement `-c` option for translation comments.
